import type { Itinerary } from "./itinerary";
import type { Flight } from "./flights";

export const samplePrompt =
  "I have 1800 euros. I want to visit Japan for 12 days in April. I love anime, sushi, photography and nature. I prefer boutique hotels under 120 euros per night.";

export const sampleFlights: Flight[] = [
  {
    from: "LIS",
    fromCity: "Lisbon",
    to: "CDG",
    toCity: "Paris",
    departure: "2026-09-01T07:35:00+01:00",
    arrival: "2026-09-01T11:05:00+02:00",
    airline: "TAP Air Portugal",
    flightNumber: "TP440",
    terminal: "1",
    gate: "14",
    baggage: "1x23kg checked",
    bookingRef: "QX7R4L",
  },
  {
    from: "CDG",
    fromCity: "Paris",
    to: "HND",
    toCity: "Tokyo",
    departure: "2026-09-01T13:30:00+02:00",
    arrival: "2026-09-02T08:55:00+09:00",
    airline: "Air France",
    flightNumber: "AF276",
    terminal: "2E",
    baggage: "1x23kg checked",
    bookingRef: "QX7R4L",
  },
];

export const sampleItinerary: Itinerary = {
  title: "Japan in Bloom",
  city: "Tokyo, Kyoto & Osaka",
  country: "Japan",
  summary:
    "Twelve days across Tokyo, Hakone, Kyoto and Osaka, timed for cherry blossom season and built around anime districts, sushi counters and quiet temple mornings. Boutique stays throughout, all under 120 euros a night, with the whole trip inside your 1,800 euro budget.",
  currency: "EUR",
  totalCost: 1780,
  budget: {
    accommodation: 570,
    flights: 580,
    food: 280,
    transport: 140,
    activities: 90,
    shopping: 50,
    emergency: 70,
  },
  hotels: [
    {
      name: "Onsen Ryokan Yuen Shinjuku",
      area: "Shinjuku, Tokyo",
      pricePerNight: 110,
      style: "modern ryokan",
      note: "Rooftop open-air onsen with skyline views, five minutes from Shinjuku station.",
    },
    {
      name: "Rinn Gion Hanatouro",
      area: "Gion, Kyoto",
      pricePerNight: 85,
      style: "machiya boutique",
      note: "Converted townhouse on a lantern-lit lane, walking distance to Kiyomizu-dera.",
    },
    {
      name: "Hotel She, Osaka",
      area: "Benten-cho, Osaka",
      pricePerNight: 70,
      style: "indie boutique",
      note: "Record players in every room and a young local crowd, two stops from Dotonbori.",
    },
  ],
  days: [
    {
      day: 1,
      title: "Landing in Neon",
      area: "Shinjuku, Tokyo",
      breakfast: { name: "On the flight", note: "Land at Haneda around midday, so breakfast happens in the air.", cost: 0 },
      morning: { name: "Airport to Shinjuku", note: "Grab a Welcome Suica at Haneda, then ride the Keikyu line into the city.", cost: 5, lat: 35.5494, lng: 139.7798 },
      lunch: { name: "Ichiran Shinjuku", note: "Solo-booth tonkotsu ramen, the gentlest possible landing meal.", cost: 9, lat: 35.6938, lng: 139.7034 },
      afternoon: { name: "Shinjuku Gyoen", note: "Slow first walk under the cherry trees to beat jet lag with daylight.", cost: 3, lat: 35.6852, lng: 139.71 },
      dinner: { name: "Omoide Yokocho", note: "Yakitori under paper lanterns in the alley photographers dream about.", cost: 15, lat: 35.6931, lng: 139.6996 },
      night: { name: "Tokyo Metropolitan Building", note: "Free 45th-floor observatory, city lights to the horizon.", cost: 0, lat: 35.6896, lng: 139.6917 },
      travel: "Keikyu line from Haneda plus two metro hops, about 75 minutes total transit.",
      dailyCost: 32,
      tip: "Buy the Welcome Suica at the airport machine; it works on every train, bus and konbini for the whole trip.",
    },
    {
      day: 2,
      title: "Old Tokyo, Electric Town",
      area: "Asakusa & Akihabara",
      breakfast: { name: "Kissaten morning set", note: "Old-school coffee shop toast-and-egg set near Asakusa.", cost: 6, lat: 35.7119, lng: 139.7983 },
      morning: { name: "Senso-ji Temple", note: "Arrive before 8am to shoot the Kaminarimon gate without crowds.", cost: 0, lat: 35.7148, lng: 139.7967 },
      lunch: { name: "Standing sushi, Akihabara", note: "Counter sushi at half the sit-down price, eaten shoulder to shoulder with locals.", cost: 12, lat: 35.6984, lng: 139.7731 },
      afternoon: { name: "Akihabara deep dive", note: "Mandarake, Super Potato and the retro floors of Radio Kaikan for anime and game treasure.", cost: 20, lat: 35.6987, lng: 139.7714 },
      dinner: { name: "Kanda izakaya lane", note: "Smoky counter izakaya under the train tracks, order the day's sashimi.", cost: 18, lat: 35.6918, lng: 139.7708 },
      night: { name: "Mario kart-free Akihabara neon walk", note: "The billboards are the show; tripod shots from the Manseibashi bridge.", cost: 0, lat: 35.6975, lng: 139.7708 },
      travel: "Ginza line between Asakusa and Akihabara, roughly 40 minutes of trains all day.",
      dailyCost: 56,
      tip: "Most Akihabara shops open at 10 or 11am; do the temple first and arrive at the stores as shutters go up.",
    },
    {
      day: 3,
      title: "Shibuya Crossing Day",
      area: "Shibuya & Harajuku",
      breakfast: { name: "Onigiri from 7-Eleven", note: "Konbini breakfast is a genuine Japanese institution, not a compromise.", cost: 4 },
      morning: { name: "Meiji Shrine", note: "Gravel paths and giant torii inside a forest planted a century ago.", cost: 0, lat: 35.6764, lng: 139.6993 },
      lunch: { name: "Harajuku Gyoza Lou", note: "Legendary cheap gyoza two lanes off Takeshita Street.", cost: 8, lat: 35.6702, lng: 139.7043 },
      afternoon: { name: "Takeshita Street & Cat Street", note: "Harajuku fashion chaos, then vintage shops as the street calms down.", cost: 10, lat: 35.6716, lng: 139.7031 },
      dinner: { name: "Uobei Shibuya", note: "High-speed conveyor sushi delivered on rails, absurd and delicious.", cost: 14, lat: 35.6591, lng: 139.6987 },
      night: { name: "Shibuya Sky", note: "Book the sunset slot: the crossing from 229 meters as the neon switches on.", cost: 16, lat: 35.6585, lng: 139.7013 },
      travel: "Everything is walkable between Harajuku and Shibuya; under 30 minutes of trains.",
      dailyCost: 52,
      tip: "Shibuya Sky sunset tickets sell out days ahead; book online the moment you know your dates.",
    },
    {
      day: 4,
      title: "Anime Pilgrimage",
      area: "Nakano & Shinjuku",
      breakfast: { name: "Hotel onsen, then coffee", note: "Morning rooftop bath at the ryokan before the day starts.", cost: 5 },
      morning: { name: "Nakano Broadway", note: "Four floors of vintage anime cels, figures and manga, calmer and cheaper than Akihabara.", cost: 15, lat: 35.7091, lng: 139.6657 },
      lunch: { name: "Aoyama Curry, Nakano", note: "Thick Japanese curry in a ten-seat shop under the arcade.", cost: 9, lat: 35.7076, lng: 139.6659 },
      afternoon: { name: "Shimokitazawa", note: "Record stores, vintage clothes and back-alley coffee, Tokyo's best aimless afternoon.", cost: 10, lat: 35.6613, lng: 139.6683 },
      dinner: { name: "Shinjuku Kappo Nakajima", note: "Michelin-listed sardine kaiseki that costs less than most burgers at lunch, splurge lightly at dinner.", cost: 25, lat: 35.6904, lng: 139.7005 },
      night: { name: "Golden Gai", note: "Two-hundred bars the size of closets; pick one with an open stool and say hello.", cost: 12, lat: 35.6938, lng: 139.7049 },
      travel: "Chuo line out to Nakano, Odakyu line to Shimokitazawa, about 50 minutes total.",
      dailyCost: 76,
      tip: "In Golden Gai, look for bars without a cover charge sign, and always greet the master when you duck in.",
    },
    {
      day: 5,
      title: "Kamakura Sea Day",
      area: "Kamakura day trip",
      breakfast: { name: "Ekiben at Tokyo Station", note: "Pick a boxed breakfast for the train ride south.", cost: 8, lat: 35.6812, lng: 139.7671 },
      morning: { name: "Great Buddha of Kamakura", note: "The 13-meter bronze Daibutsu sitting in the open air since 1252.", cost: 3, lat: 35.3167, lng: 139.5361 },
      lunch: { name: "Komachi-dori street food", note: "Shirasu rice bowls and sweet potato soft serve along the temple lane.", cost: 11, lat: 35.3192, lng: 139.5502 },
      afternoon: { name: "Enoden line to Enoshima", note: "The little green train hugs the coast; sit on the sea side for the view Slam Dunk made famous.", cost: 7, lat: 35.2996, lng: 139.4813 },
      dinner: { name: "Shonan seafood diner", note: "Grilled fish set watching surfers pack up for the day.", cost: 15, lat: 35.3015, lng: 139.4863 },
      night: { name: "Back to Shinjuku", note: "Easy train ride home; rest the legs for the Hakone transfer tomorrow.", cost: 0 },
      travel: "JR to Kamakura, Enoden along the coast, JR home. Around 3 hours of scenic trains.",
      dailyCost: 44,
      tip: "The Kamakurakoko-mae railroad crossing is the famous anime shot; go at golden hour and stand well clear of the tracks.",
    },
    {
      day: 6,
      title: "Hakone Mountain Air",
      area: "Hakone",
      breakfast: { name: "Bakery at Shinjuku station", note: "Grab pastries before the Romancecar to the mountains.", cost: 5 },
      morning: { name: "Hakone Open-Air Museum", note: "Sculptures scattered across a mountain valley, with a Picasso pavilion.", cost: 12, lat: 35.2444, lng: 139.0503 },
      lunch: { name: "Gora soba house", note: "Hot soba after the museum, ordered from a vending machine ticket.", cost: 9, lat: 35.2472, lng: 139.0481 },
      afternoon: { name: "Ropeway over Owakudani", note: "Cable car above the sulfur vents, with Mount Fuji appearing on clear days.", cost: 15, lat: 35.2444, lng: 139.0194 },
      dinner: { name: "Ryokan kaiseki-lite set", note: "Simple multi-course dinner near Lake Ashi.", cost: 20, lat: 35.2033, lng: 139.0255 },
      night: { name: "Onsen soak", note: "Public hot spring bath under the stars, the whole reason Hakone exists.", cost: 8, lat: 35.2323, lng: 139.1069 },
      travel: "Odakyu Romancecar from Shinjuku, then the Hakone loop of switchback train, cablecar and ropeway.",
      dailyCost: 69,
      tip: "The Hakone Freepass covers every leg of the loop and pays for itself by mid-afternoon.",
    },
    {
      day: 7,
      title: "First Light in Kyoto",
      area: "Higashiyama, Kyoto",
      breakfast: { name: "Shinkansen bento", note: "Ride the bullet train west; Fuji sits on the right side of the carriage.", cost: 9 },
      morning: { name: "Kiyomizu-dera", note: "The wooden terrace floats over a sea of cherry trees in April.", cost: 4, lat: 34.9949, lng: 135.785 },
      lunch: { name: "Nishiki Market grazing", note: "Kyoto's kitchen: tamagoyaki skewers, mochi and tiny sea snacks stall to stall.", cost: 12, lat: 35.005, lng: 135.7649 },
      afternoon: { name: "Sannenzaka & Ninenzaka", note: "Preserved sloping lanes between temples, best photographed in late light.", cost: 0, lat: 34.9966, lng: 135.7811 },
      dinner: { name: "Gion Kappa izakaya", note: "Obanzai small plates, Kyoto home cooking done at a counter.", cost: 18, lat: 35.0037, lng: 135.7751 },
      night: { name: "Gion after dark", note: "Lantern-lit Hanamikoji street; walk quietly, geiko are commuting to work.", cost: 0, lat: 35.0031, lng: 135.7754 },
      travel: "Shinkansen Tokyo to Kyoto in 2h15, then buses and feet.",
      dailyCost: 43,
      tip: "Kiyomizu-dera opens at 6am, two hours before the tour buses; it is a different temple at dawn.",
    },
    {
      day: 8,
      title: "Bamboo and River Mist",
      area: "Arashiyama, Kyoto",
      breakfast: { name: "% Arabica Arashiyama", note: "Cult espresso bar on the riverbank, in the queue by 8am.", cost: 6, lat: 35.0135, lng: 135.6783 },
      morning: { name: "Bamboo Grove", note: "Green light and creaking stalks; before 8:30am you will have stretches to yourself.", cost: 0, lat: 35.017, lng: 135.671 },
      lunch: { name: "Tofu kaiseki at Shoraian", note: "Silky yudofu in a hidden villa above the river, the great Kyoto lunch deal.", cost: 20, lat: 35.0109, lng: 135.6744 },
      afternoon: { name: "Iwatayama Monkey Park", note: "Twenty-minute climb to wild macaques and the best free view over Kyoto.", cost: 4, lat: 35.0128, lng: 135.6778 },
      dinner: { name: "Kyoto Station ramen alley", note: "Regional ramen styles from all over Japan on the station's 10th floor.", cost: 11, lat: 34.9858, lng: 135.7588 },
      night: { name: "Kamo River banks", note: "Buy a drink from a konbini and join the students spaced out along the water.", cost: 3, lat: 35.0116, lng: 135.7681 },
      travel: "JR Sagano line out to Arashiyama, about 45 minutes of transit total.",
      dailyCost: 44,
      tip: "The bamboo grove is free and never closes; sunrise beats every crowd and gives the softest light.",
    },
    {
      day: 9,
      title: "Ten Thousand Torii",
      area: "Fushimi & southern Kyoto",
      breakfast: { name: "Konbini coffee and melonpan", note: "Fuel for the mountain of gates.", cost: 4 },
      morning: { name: "Fushimi Inari Taisha", note: "Climb past the tourist line at the Yotsutsuji intersection; the upper loop is nearly empty.", cost: 0, lat: 34.9671, lng: 135.7727 },
      lunch: { name: "Inari sushi at the gate", note: "Sweet tofu-wrapped rice, the shrine's namesake snack.", cost: 8, lat: 34.9686, lng: 135.7715 },
      afternoon: { name: "Fushimi sake district", note: "Canal-side warehouses and tastings at Gekkeikan's 380-year-old brewery.", cost: 6, lat: 34.9302, lng: 135.7611 },
      dinner: { name: "Pontocho alley", note: "Pick a counter on the narrow lane; spring means river-facing terraces.", cost: 22, lat: 35.0043, lng: 135.7709 },
      night: { name: "Philosopher's Path at dusk", note: "Cherry petals on the canal with almost nobody left walking it.", cost: 0, lat: 35.0271, lng: 135.7944 },
      travel: "Keihan line links Fushimi, the sake district and central Kyoto; about an hour total.",
      dailyCost: 40,
      tip: "Start Fushimi Inari by 7am; the full summit loop takes two hours and the light through the gates is best early.",
    },
    {
      day: 10,
      title: "Deer Bowing in Nara",
      area: "Nara day trip",
      breakfast: { name: "Kyoto station bakery", note: "Quick pastries before the express to Nara.", cost: 5 },
      morning: { name: "Nara Park", note: "Twelve hundred sacred deer that bow for crackers; keep your map out of biting range.", cost: 2, lat: 34.6851, lng: 135.843 },
      lunch: { name: "Kamameshi Shizuka", note: "Iron-pot rice cooked to order near the park entrance.", cost: 13, lat: 34.6828, lng: 135.8399 },
      afternoon: { name: "Todai-ji Great Buddha Hall", note: "The world's largest bronze Buddha inside one of the largest wooden buildings anywhere.", cost: 5, lat: 34.689, lng: 135.8398 },
      dinner: { name: "Osaka Dotonbori arrival", note: "Train to Osaka, check in, then takoyaki straight from the stand.", cost: 12, lat: 34.6687, lng: 135.5013 },
      night: { name: "Glico sign & canal walk", note: "Osaka's neon riverfront, camera out, okonomiyaki smell everywhere.", cost: 0, lat: 34.6685, lng: 135.5011 },
      travel: "Kintetsu express Kyoto to Nara, then Nara to Osaka-Namba; about 2 hours of trains.",
      dailyCost: 37,
      tip: "Buy deer crackers only after stowing everything loose; the deer know exactly what the paper wrapper sounds like.",
    },
    {
      day: 11,
      title: "Osaka Eats Everything",
      area: "Namba & Den Den Town",
      breakfast: { name: "Kuromon Ichiba Market", note: "Grilled scallops and fresh uni for breakfast at Osaka's kitchen market.", cost: 12, lat: 34.6659, lng: 135.5063 },
      morning: { name: "Den Den Town", note: "Osaka's answer to Akihabara, with better prices on figures and retro games.", cost: 15, lat: 34.6592, lng: 135.5064 },
      lunch: { name: "Mizuno okonomiyaki", note: "Ninety-year-old griddle institution in Dotonbori, worth the queue.", cost: 12, lat: 34.6678, lng: 135.5023 },
      afternoon: { name: "Osaka Castle Park", note: "The keep above the moats, ringed by late cherry blossoms in mid-April.", cost: 6, lat: 34.6873, lng: 135.5262 },
      dinner: { name: "Kushikatsu Daruma", note: "Deep-fried skewers with the one sacred rule: never double-dip the sauce.", cost: 15, lat: 34.6524, lng: 135.5061 },
      night: { name: "Umeda Sky Building", note: "The floating garden observatory, Osaka's grid glowing in every direction.", cost: 12, lat: 34.7052, lng: 135.4894 },
      travel: "Midosuji line spine all day, around 40 minutes of metro.",
      dailyCost: 72,
      tip: "Kuromon market stalls start closing mid-afternoon; it is a morning place, not an evening one.",
    },
    {
      day: 12,
      title: "Last Bowl, Last Bow",
      area: "Osaka, departure",
      breakfast: { name: "Hotel coffee, packed bags", note: "Slow morning, luggage to the lobby.", cost: 4 },
      morning: { name: "Shinsekai stroll", note: "Retro Osaka under the Tsutenkaku tower for final street photos.", cost: 0, lat: 34.6525, lng: 135.5063 },
      lunch: { name: "Last ramen at Kansai Airport", note: "One final bowl airside before the flight home.", cost: 10, lat: 34.4342, lng: 135.2441 },
      afternoon: { name: "Fly home", note: "Nankai Rapi:t train to KIX, window seat, film the takeoff.", cost: 12 },
      dinner: { name: "In the air", note: "Airline dinner over Siberia while you sort 4,000 photos.", cost: 0 },
      night: { name: "Home", note: "Start the shortlist of what you missed; everyone plans the second trip on the flight back.", cost: 0 },
      travel: "Rapi:t express from Namba to Kansai Airport, 38 minutes.",
      dailyCost: 26,
      tip: "Duty-free matcha KitKats are the correct gift and they are cheaper in the airport Lawson than in the souvenir hall.",
    },
  ],
  packing: [
    "Light layers for 8 to 19 degree April days",
    "Compact rain jacket for spring showers",
    "Broken-in walking shoes, 15,000 steps daily is normal",
    "Camera plus a spare SD card and battery",
    "Portable phone battery for map-heavy days",
    "Type A plug adapter",
    "Coin purse, Japan still runs on change",
    "Small folding day bag for markets",
    "Hay fever tablets, cedar pollen peaks in spring",
    "Quick-dry towel for onsen visits",
  ],
  safety: [
    "Japan is exceptionally safe; petty theft is rare even in nightlife districts",
    "Install the NHK World app for earthquake and typhoon alerts in English",
    "Last trains run around midnight; missing one means a pricey taxi",
    "Carry your passport, it is legally required and needed for tax-free shopping",
  ],
  weather:
    "April means 8 to 19 degrees, mostly sunny with occasional showers. Cherry blossoms peak in Tokyo in the first week and in Kyoto slightly later.",
  bestTime:
    "Late March to mid-April for cherry blossoms, or late November for autumn leaves. April has the best light for photography and mild hiking weather.",
  hiddenGems: [
    { name: "Yanaka Ginza, Tokyo", note: "A shopping street that survived the war; old Tokyo at street-cat pace." },
    { name: "Shimokitazawa vinyl basements", note: "Record shops where the owner will play you anything before you buy." },
    { name: "Fushimi sake canal at dusk", note: "Edo-period warehouses reflected in the water, ten minutes from the crowds." },
    { name: "Nakazakicho, Osaka", note: "A bombed-war-survivor pocket of lanes now full of tiny cafes and zine shops." },
  ],
  photoSpots: [
    { name: "Shibuya Sky at sunset", note: "The crossing from above as the city switches to neon." },
    { name: "Bamboo Grove before 8am", note: "Empty path, green cathedral light." },
    { name: "Fushimi Inari upper loop", note: "Unbroken tunnels of vermilion gates with no one in frame." },
    { name: "Kamakurakoko-mae crossing", note: "The seaside railway crossing from the Slam Dunk opening." },
    { name: "Omoide Yokocho at night", note: "Lantern smoke and salarymen, shoot wide open at f1.8." },
  ],
  rainPlan: [
    "teamLab Planets Tokyo, book the first morning slot",
    "Kyoto Railway Museum, genuinely great even if you do not care about trains",
    "Nishiki Market and the covered Teramachi arcades",
    "An afternoon sento bath followed by a manga cafe",
    "Umeda underground city, Osaka barely needs the surface",
  ],
};
